OpenLake/Leaderboard-Pro

- README.md
Updated Readme file.
This time spelling of regularly is being corrected in 2nd last line of the problem topic.
not required 
Keep a regular check on the readme file and avoid spelling errors if possible 
@yatendra1999 @KShivendu @Gopal-Dahale 
Not required 
Just corrected the spelling of a word so not required
>  [RR] Update spelling of regularly again

- api/leaderboard/admin.py
- api/leaderboard/asgi.py
- api/leaderboard/celery.py
- api/leaderboard/models.py
- api/leaderboard/scripts/populate.py
- api/leaderboard/serializers.py
- api/leaderboard/settings.py
- api/leaderboard/tests.py
- api/leaderboard/urls.py
- api/leaderboard/views.py
- api/leaderboard/wsgi.py
- api/manage.py
This PR resolves issue #21 
- applied black and flake8 to files present under api folder
- black
- flake8
- Naming convention of classes can be fixed as they should be camelcase instead of snakecase
- Some constants like urls can be moved to separate constants file and can be imported from their
@Harshith-19 
The above image shows violation in migration files which can be ignored.
> pep8 and black formatting

- app/package-lock.json
- app/src/App.js
- app/src/components/CodechefTable.js
Issue#26 To Display Codechef user information.
CodechefTable for LeaderBoard regading Issue#26.
Created a Frontend for Codechef Table that fetches the details from backend api and displays it in table format.
No extra dependencies .
1) Include Routing for Different Tables in the leaderboard.
@Harshith-19
> Created Frontend for CodechefTable Section regarding Issue#26.

- app/package-lock.json
- app/package.json
- app/src/App.js
- app/src/components/Navbar.js
Included Routing for tables of different platforms and Updated the navigation Bar links accordingly. In response to the issue#29.
Feature to  navigate between  different tables is added using react router dom v5.2.0 and updated the navbar buttons for the same so that the tables will not clutter the home page and will be displayed on the will of the user.
react-router-dom v5.2.0 is required along with previous dependencies.
The user Interface is a bit cluttered and and not symmetrical hence its design can be improved .
@Harshith-19
> Routing Using React Router and Updated Navbar As per Issue#26.

- api/leaderboard/settings.py
> Updated settings.py

- api/leaderboard/admin.py
- api/leaderboard/celery.py
- api/leaderboard/models.py
- api/leaderboard/serializers.py
- api/leaderboard/urls.py
- api/leaderboard/views.py
Solved #25 
All the variable names have been now converted to lowerCamelCase.
None
None
@Harshith-19 
None
> Updated variable names to lowerCamelCase

- api/leaderboard/admin.py
- api/leaderboard/models.py
- api/leaderboard/serializers.py
- api/leaderboard/views.py
Spelling error
I changed the spelling of "openlakeContributer" --> "openlakeContributor"
-   Fixed spelling error.
@VickyMerzOwn and @Harshith-19
> Fixed spelling error.

- app/package-lock.json
- app/package.json
- app/src/App.js
- app/src/components/CodechefTable.js
- app/src/components/CodeforcesTable.js
- app/src/components/Navbar.js
- app/src/theme.js
Improvements in UI and dark mode
1 Tables UI is better.
2 Dark mode with toggle in navbar and retention of preference on refresh.
Material UI
Responsive for smaller screens
@Harshith-19
> Dark Mode and UI Improvements.

- app/src/components/CodechefTable.js
Integration of Backend & frontend and updated table UI as per Issue #19 
Frontend is now  able to fetch and display the data of codechef table.
Removed Progress column.
No extra dependencies.
@Harshith-19
> Codehef Backend - frontend Integration

- app/package-lock.json
- app/package.json
- app/src/App.js
- app/src/components/CodeforcesTable.js
- app/src/components/Navbar.js
- app/src/components/OpenlakeTable.js
This code solve the issue #39 
Created Openlake Table
@Harshith-19
> Successfully created Openlake Table

- app/src/App.js
- app/src/components/CodechefTable.js
- app/src/components/OpenlakeTable.js
Pull request for issue #18 
Connected Openlake Table with Backend 
@Harshith-19
> Connected Openlake Table with Backend 

- app/src/components/CodechefTable.js
- app/src/components/GithubTable.js
issue #17 resolved
@Harshith-19
> Integrate backend of Github leaderboard to the frontend

- app/src/App.js
- app/src/components/CodechefTable.js
- app/src/components/CodeforcesTable.js
- app/src/components/GithubTable.js
- app/src/components/Navbar.js
- app/src/components/OpenlakeTable.js
Fixed the Dark Mode Bug and improved the frontend colours based on the same.
Now the website does not reload on switching the dark mode.
No extra dependencies required.
Login page and api fetching.
@Harshith-19
> Dark Mode Fix and frontend improvements

- app/package.json
- app/src/App.js
- app/src/components/LeetcodeGraphs.js
- app/src/components/LeetcodeRankingsCCPS.js
[#63](https://github.com/OpenLake/Leaderboard-Pro/issues/63)
With this feature, users can gain valuable insights into an individual's performance history and track their progress over time.
@krishnan05
> Added graphs feature

- api/leaderboard/celery.py
- api/leaderboard/root.py
- api/leaderboard/serializers.py
- api/leaderboard/settings.py
- To save codechef, leetcode and github user details in database using serializers to increase efficiency
- Added leetcode code URL to API root
- Updating codechef user details and validation in celery with the help of django serializers
- Updating leetcode user details and validation in celery with the help of django serializers
- Updating github user details and validation in celery with the help of django serializers
- Adding leetcode url to API root
None
- Saving codeforces user details using celery and django serializers
@krishnan05
> Save Codechef, Leetcode, Github user details using serializers

- app/src/components/CodechefTable.js
- app/src/components/CodeforcesTable.js
- app/src/components/GithubTable.js
- app/src/components/LeetcodeTable.js
- app/src/components/OpenlakeTable.js
- app/src/hooks/useScreeWidth.js
Issue
close [#68](https://github.com/OpenLake/Leaderboard-Pro/issues/68)
- Improved CodeforcesTable, CodechefTable, GithubTable, LeetcodeTable and OpenLakeTable
- Added a new folder hooks and a new hook 
None
@krishnan05 
https://github.com/OpenLake/Leaderboard-Pro/assets/109169835/08283689-52e4-41f8-b1aa-39676ff00d7b
> Added responsive design to contest tables

- api/leaderboard/api/views.py
- api/leaderboard/celery.py
- api/leaderboard/serializers.py
- api/leaderboard/settings.py
- api/leaderboard/urls.py
- api/leaderboard/views.py
- Created celery job for codeforces
- Created celery job for codeforces to asynchronously fetch the details
- The details are being saved using serializer
None
- Create user profile API to gather all the information regarding the user
@krishnan05
> created celery job for codeforces

- app/src/components/GithubTable.js
Issue
close #75
Solved and friend list integration with the new MongoDB URL.
- Change new Api URL, github add, github drop, github friends list.
None
Leetcode ranking UI Enhancement
@krishnan05
- [x ] Followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html).
> solved Github friend's add friend with new url

- app/src/components/LeetcodeTable.js
Issue
close #73 
Solved Leetcode Friend addition, deletion and friend's list integration with new mongodb url
- Change new Api URL, leetcode add, leetcodedrop, leetcode friends list.
None
None
@krishnan05
> solved leetcode friend add etc with new url

- api/leaderboard/root.py
- api/leaderboard/serializers.py
- api/leaderboard/urls.py
- api/leaderboard/users.py
- Profile Details API
- Created an API which gives details of an user in his profile page
- Returns data from all the platforms
None
- Remove any unwanted code present
@krishnan05
> profile details API

- app/package-lock.json
- app/package.json
- app/src/App.css
- app/src/components/Footer.js
- app/src/components/GoToTop.js
- app/src/components/Login.js
- app/src/components/Navbar.js
- app/src/components/SignIn.js
- app/src/components/SignUp.js
- Enhancement
- Before
- After
None
- Signup and Login form Enhancement
@krishnan05
> Improved Nav and Footer 

- README.md
Improvements done in documentation
Fix #84 
@krishnan05
> Improve Documentation #84 [RR]

- README.md
There is already `migrate()`  used when we run make dev so removing it would be beneficial for new developers so that they do not get more confused. Fixes #84 
None
None
> Removing `make migrate` from installation step

- README.md
Added macos installation in readme
Closes #104
> Added macos installation

- .gitignore
- Dockerfile
- README.md
Dockerised the project for easy setup and insallation.
Created dockerfile with all the dependencies.
Closes  #103
> Dockerised the project

- app/src/App.js
- app/src/Context/AuthContext.js
- app/src/components/Profile.js
Make a landing page for the Google auth sign-up by fixing the profile page which already has a built-in CP username update section.
- Fix Profile page and remove the user tasks from the UI temporarily
- Make the front-end store some info about the CP usernames.
@amaydixit11
> [DEVLABS-2025] Make a landing page for the Google auth sign-up

- api/leaderboard/friends.py
- app/src/components/CodechefTable.js
- app/src/components/CodeforcesTable.js
- app/src/components/GithubTable.js
- app/src/components/LeetcodeTable.js
- app/src/components/Navbar.js
- app/src/components/OpenlakeTable.js
Fixes the crashes in the friends list pages as well as making it fully functional with adding and deleting friends. Closes #123.
- Fixed the friends list page functionality by adding an empty check for the filteredusers object
- Fixed the UI a bit to make it centered as well as not scroll over the navbar due to z-index issues
@amaydixit11
> [DEVLABS-2025] Fix friends list page

- app/src/components/CodechefTable.jsx
- app/src/components/GithubTable.jsx
- app/src/components/LeetcodeTable.jsx
Some files still had localhost set as the backend so fix it to environment variable set up.
@amaydixit11
> [DEVLABS-2025] Fix localhost leftover in some files of frontend.

- app/eslint.config.mjs
- app/package.json
- app/pnpm-lock.yaml
- app/src/components/CodechefTable.jsx
- app/src/components/CodeforcesTable.jsx
- app/src/components/GithubTable.jsx
- app/src/components/LeetcodeTable.jsx
- app/src/components/OpenlakeTable.jsx
Due to some package import errors and ESLint configuration errors, Vercel deployment of the site was failing. This PR intends to fix that error.
@amaydixit11
> Try to fix the Vercel deployment error.

- app/src/components/HomePage.jsx
If the user doesn't link their CP usernames, the site will not be able to show their info and might crash if there is no checks to see this. This PR intends to add checks to make sure the site doesn't crash. This PR also adds the bottom tabs which will later contain useful info about the user and their activity across multiple sites. Part of #132.
- Added nullish checks to check whether the data needed for the respective card is present or show N/A when not present
-  Added TabsView to show the different tabs on the dashboard as discussed previously
- Add the actual components in the tabs.
@amaydixit11 
- ### TabsView<img width="1851" height="1115" alt="image" src="https://github.com/user-attachments/assets/6d4bf3a7-8898-410c-89a0-5ff600c8dd50" />
- ### When data is not present<img …
> [DEVLABS-2025] Fix an issue in dashboard and add tabs with placeholder text

- README.md
- api/.env.backend
- api/leaderboard/api/firebase.py
- api/leaderboard/settings.py
- app/.env.frontend
- app/src/Context/firebase.config.js
- compose.yml
- docker/backend.Dockerfile
- docker/frontend.Dockerfile
This PR containerizes the web app to be able to run it without issues with a single command on your local machine.
> feat: Add dockerization for easy running and deployment of code in local machines
